#title{
  background-color: darkseagreen;
  text-align: 50%;
}

.container-fluid{
  padding:3% 15%;
}

h1 {
  font-family:'Montserrat';
  font-weight: bold;
  font-size: 4rem ;
  line-height: 1.5;
  color: white;
}
h2{
  font-family:'Indie Flower';
  font-size: 3rem;
  line-height: 1.5;
  font-weight:bold;
  margin-bottom: 5%;
}
h3 {
  font-family:"Montserrat";
  font-weight: "bold";
}

p{
  color:gray;
}
/*--navgation bar--!*/
.navbar{
  padding-bottom:4.5rem;
  padding:0 0 4.5rem;
  font-size: 1.5rem;
}
.navbar-brand {
font-family: "Ubuntu"; 
font-size: 1.5rem;
font-weight:bold;
: white;
}

.nav-item{
  padding:0 0 1rem;
}

.navlink{
  font-family: 'Montserrat', sans-serif; 
  font-size:1.2rem;
}
/* COGS3 studyBuddy specific styles go here. */

/*button*/
.download-button{
  margin:10% 3% 5% 0;
}
/*title image*/
.title-image{
  width:85%;
  transform: rotate(0deg);
  position: absolute;
}
/*features*/
#features{
  z-index: 5;
  background-color: white;
  padding:7% 15%;
  position: relative;
}
.feature-box{
  text-align: center;
  padding: 5%; 
}
.icons{
  color: indianred;
  margin-bottom: 1rem;
}
.icons:hover{
  color:#2fb6fec0 ;
}
/*Testimonal sections*/
#testimonials {
  text-align: center;
  background-color:darkseagreen; (160, 95, 125);
  padding:7% 15%;
}

.carousel-item {
  padding: 7% 15%;
}
/*testimonial image*/
.testimonial-image{
  width: 25%;
  border-radius: 50%;
}
#press{
  background-color: darkseagreen;
  text-align: center;
}
.press-logo{
 width: 10%;
 margin: 30px 20px 50px; 
}
#pricing{
  background-color: white;
  padding: 100px;
  text-align: center;
}
.pricing-title{
  font-family: 'Ubuntu';
  font-weight: bold;
}
.price-paragraph{
  font-size: 20px;
  font-weight: bold;
  color:black;
}
.pricing-header{
  color:black ;
  font-family: 'Monserrat';
  font-weight: bold;
}
.card-title{
  font-family:'viga';
  font-weight:bold;
}
.pricing-column{
  padding: 3% 4%
}
/*Call To Action Section CTA*/
#cta{
  background-color:darkseagreen;
  color:white;
  padding:7% 15%;
  text-align: center;
}
.cta-heading{
font-family: 'Monserrat';
font-weight: bold;
font-size: 3.5rem;
line-height: 1.5;
}

/*footer section*/
#footer{
  padding: 7% 15%;
  text-align: center;
}
.social-icon{
  margin: 20px 10px;
  font-size: 32px;
}
/*Media Query*/

@media(max-width: 1028px){
  #title{
    text-align: center;
  } 
  .title-image{
    position:static;
    transform:rotate(0)
  }
